### ISSUE TITLE
Data files?

### ISSUE THREAD

**Issue by bmabey** [FlorianKrach/LMS-model#1]
Hi @FlorianKrach,
Thanks for posting the study's code on github! Would you mind uploading the input and output datafiles from this script? Specicially these files:

> data_file_name = 'data_reference_values_v17.xlsx'  # the name of the data file
> save_output_file_name = 'data/auto_overview.xlsx'

I realize the reference values should be the same as the data in the tables in the paper but having it in excel format along with your percentiles would make using the data far easier. 

Before I found this repo I had already extracted the values of the percentiles [here](https://github.com/bmabey/body-comp-data) but getting the actual data from you would be far better.

**Comment by bmabey** [comment]
Actually, I just found what I needed in your other repo: https://github.com/FlorianKrach/scientific-LMS-zscore-app/tree/master/data

Thanks for publishing all of this!

**Comment by FlorianKrach** [comment]
Great! I added the link to the data to the README, so it should be easier to find now.
